# Generated by Django 3.0.6 on 2020-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainername', models.CharField(max_length=50)),
                ('victimename', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('dateofincedence', models.CharField(max_length=30)),
                ('timeofincedence', models.CharField(max_length=30)),
                ('timeoffirregistration', models.DateTimeField(auto_now_add=True)),
                ('complaintype', models.CharField(max_length=30)),
                ('thana', models.TextField()),
            ],
        ),
    ]
