# Generated by Django 3.0.6 on 2020-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_fir'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
