# Generated by Django 3.0.6 on 2020-07-29 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fir', '0004_auto_20200702_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargesheetfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filefield', models.FileField(upload_to='')),
                ('approverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
