# Generated by Django 3.0.6 on 2020-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thananame', models.CharField(max_length=50)),
                ('contact', models.TextField()),
            ],
        ),
    ]
