# Generated by Django 3.0.6 on 2020-07-01 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thana',
            name='location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
